name: Terragrunt Apply
description: Terragrunt Apply

runs:
  using: composite
  steps:

    - uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ env.ARM_CLIENT_ID }}","clientSecret":"${{ env.ARM_CLIENT_SECRET }}","subscriptionId":"${{ env.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ env.ARM_TENANT_ID }}"}'
    
    - name: "Terragrunt Init, Validate and Plan"
      shell: bash
      working-directory: "./${{ inputs.environment }}"
      run: |
        set -xeuo pipefail
        terragrunt init --terragrunt-non-interactive
        terragrunt run-all validate --terragrunt-ignore-dependency-errors
        # Run default plan with output
        terragrunt run-all plan -no-color -input=false -out tfplan --terragrunt-ignore-dependency-errors

    - name: "Terragrunt Apply"
      shell: bash
      working-directory: "./${{ inputs.environment }}"
      env:
        TERRAGRUNT_NON_INTERACTIVE: true
      run: |
        terragrunt run-all apply -no-color tfplan --terragrunt-ignore-dependency-errors
