name: Terraform Prerequisites
description: Terraform Prerequisites

runs:
  using: composite
  steps:
    # - name: Set up TFLint
    #   uses: terraform-linters/setup-tflint@v1

    # - name: Initialize TFLint
    #   shell: bash
    #   run: tflint --init

    # - name: Run TFLint
    #   shell: bash
    #   run: tflint --chdir="./${{ inputs.environment }}"

    # - name: Run TFsec
    #   uses: aquasecurity/tfsec-action@v1.0.3
    #   with:
    #     working-directory: "./${{ inputs.environment }}"

    - name: Generate a token
      id: generate-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}

    - name: tfsec
      uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
      with:
        tfsec_args: --soft-fail
        working_directory: "./${{ inputs.environment }}"
        github_token: ${{ steps.generate-token.outputs.token }}
