name: "Infra-Deploy"

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - nonprod/**/terragrunt.hcl
      - preprod/**/terragrunt.hcl

  workflow_dispatch:
    inputs:
      runnerName:
        type: choice
        description: "Runner Name"
        required: true
        default: ubuntu-latest
        options:
          - ubuntu-latest

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  generate-folder-names:
    name: pr create
    # runs-on: ${{ github.event.inputs.runnerName }}
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.directory-matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find Terragrunt Changes
        id: find-terragrunt-changes
        uses: tj-actions/changed-files@v45
        with:
          dir_names: "true"
          files: |
            nonprod/**
            preprod/**
            prod/**
          files_ignore: |
            nonprod/**.md
            preprod/**.md
            prod/**.md
        continue-on-error: true

      - name: Generate Matrix
        if: ${{ steps.find-terragrunt-changes.outputs.all_changed_files }}
        uses: mtjtest001/testpublic001/.github/actions/generate-terragrunt-changes-matrix@main
        id: generate-matrix
        with:
          directories: ${{ steps.find-terragrunt-changes.outputs.all_changed_files }}

      - name: "Test"
        shell: bash
        run: |
          echo "Changed files"
          echo "${{ steps.find-terragrunt-changes.outputs.all_changed_files }}"
          echo "Matrix"
          echo "${{ steps.generate-matrix.outputs.directory-matrix }}"

  terragrunt-plan-apply-nonprod:
    if: fromJson(needs.generate-folder-names.outputs.matrix).nonprod != ''
    needs:
      - generate-folder-names
    name: Terragrunt Plan and Apply
    uses: mtjtest001/testpublic001/.github/workflows/terragrunt-plan-apply.yml@main
    with:
      environment: nonprod
    secrets: inherit

  terragrunt-plan-apply-preprod:
    if: fromJson(needs.generate-folder-names.outputs.matrix).preprod != ''
    needs:
      - generate-folder-names
    name: Terragrunt Plan and Apply
    uses: mtjtest001/testpublic001/.github/workflows/terragrunt-plan-apply.yml@main
    with:
      environment: preprod
    secrets: inherit
