name: Terragrunt Plan and Apply
on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: "Environment"
        required: true
    secrets:
      app_id_01:
        required: true
      app_key_01:
        required: true

defaults:
  run:
    shell: bash

jobs:
  terragrunt-plan:
    name: "Terragrunt Plan"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      # ARM_USE_OIDC: true
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Git Config
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Checkout
        uses: actions/checkout@v4

      - name: Terragrunt installer
        uses: autero1/action-terragrunt@v3.0.2
        with:
          terragrunt-version: v0.67.6

      # - name: Wiz Scan
      #   uses: mtjtest001/testpublic001/.github/actions/wiz@main
      #   with:
      #     environment: ${{ inputs.environment }}
      #     secrets: inherit
      #     WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
      #     WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}

      - name: Prerequisites
        uses: mtjtest001/testpublic001/.github/actions/terraform-prerequisites@main
        with:
          environment: ${{ inputs.environment }}
          secrets: inherit
          app-id: ${{ secrets.app_id_01 }}
          private-key: ${{ secrets.app_key_01 }}

      - name: Azure Authentication
        env:
          # ARM_USE_OIDC: true
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          # az login --service-principal -u $ARM_CLIENT_ID -t $ARM_TENANT_ID -p $AZURE_CLIENT_SECRET
          az login --service-principal -u "3146b07e-ced7-4128-90fc-45eaab5bc1fd" -t "553bbad8-53d4-412c-b86c-7110503b960d"-p $AZURE_CLIENT_SECRET
          az account set --subscription $ARM_SUBSCRIPTION_ID

      - name: TerragruntPlan
        uses: mtjtest001/testpublic001/.github/actions/terragrunt-plan@main
        with:
          environment: ${{ inputs.environment }}
          app-id: ${{ secrets.app_id_01 }}
          private-key: ${{ secrets.app_key_01 }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  terragrunt_apply:
    name: "Terragrunt Apply"
    if: needs.terragrunt-plan.result == 'success'
    needs: terragrunt-plan
    runs-on: ubuntu-latest
    env:
      # ARM_USE_OIDC: true
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    environment: ${{ inputs.environment }}_deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terragrunt installer
        uses: autero1/action-terragrunt@v3.0.2
        with:
          terragrunt-version: v0.67.6

      - name: TerragruntApply
        uses: mtjtest001/testpublic001/.github/actions/terragrunt-apply@main
        with:
          environment: ${{ inputs.environment }}
          secrets: inherit
